# <font color='black'>4.1 Exercise on Functions</font>

# <font color='black'>4.1 Exercise on Functions</font>

# Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def convert_length(value, unit):
    """
    Convert length between meters (m) and feet (ft).
    :param value: The numerical value to convert.
    :param unit: The unit of the input value ('m' for meters, 'ft' for feet).
    :return: Converted value with appropriate unit.
    """
    if unit == 'm':
        return value * 3.28084, 'ft'
    elif unit == 'ft':
        return value / 3.28084, 'm'
    else:
        raise ValueError("Invalid unit for length conversion")

def convert_weight(value, unit):
    """
    Convert weight between kilograms (kg) and pounds (lbs).
    :param value: The numerical value to convert.
    :param unit: The unit of the input value ('kg' for kilograms, 'lbs' for pounds).
    :return: Converted value with appropriate unit.
    """
    if unit == 'kg':
        return value * 2.20462, 'lbs'
    elif unit == 'lbs':
        return value / 2.20462, 'kg'
    else:
        raise ValueError("Invalid unit for weight conversion")

def convert_volume(value, unit):
    """
    Convert volume between liters (L) and gallons (gal).
    :param value: The numerical value to convert.
    :param unit: The unit of the input value ('L' for liters, 'gal' for gallons).
    :return: Converted value with appropriate unit.
    """
    if unit == 'L':
        return value * 0.264172, 'gal'
    elif unit == 'gal':
        return value / 0.264172, 'L'
    else:
        raise ValueError("Invalid unit for volume conversion")

def main():
    print("Unit Converter: Length, Weight, Volume")
    print("1. Length (m <-> ft)")
    print("2. Weight (kg <-> lbs)")
    print("3. Volume (L <-> gal)")

    try:
        choice = int(input("Choose the type of conversion (1-3): "))
        value = float(input("Enter the value to convert: "))
        unit = input("Enter the unit (e.g., m, ft, kg, lbs, L, gal): ").strip().lower()

        if choice == 1:
            result, new_unit = convert_length(value, unit)
        elif choice == 2:
            result, new_unit = convert_weight(value, unit)
        elif choice == 3:
            result, new_unit = convert_volume(value, unit)
        else:
            print("Invalid choice. Please select 1, 2, or 3.")
            return

        print(f"Converted value: {result:.2f} {new_unit}")
    except ValueError as e:
        print(f"Error: {e}. Please enter valid input.")
    except Exception as e:
        print(f"Unexpected error: {e}")

# Run the main function
main()


Unit Converter: Length, Weight, Volume
1. Length (m <-> ft)
2. Weight (kg <-> lbs)
3. Volume (L <-> gal)
Choose the type of conversion (1-3): 1
Enter the value to convert: 10
Enter the unit (e.g., m, ft, kg, lbs, L, gal): m
Converted value: 32.81 ft


# Task - 2:

Create a Python program that performs various mathematical operations on a list of numbers

• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimumof the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, mini-mum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values orempty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, andreturn value.

In [ ]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers.
    :param numbers: List of numerical values.
    :return: Sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculate the average of a list of numbers.
    :param numbers: List of numerical values.
    :return: Average of the numbers.
    """
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):
    """
    Find the maximum value in a list of numbers.
    :param numbers: List of numerical values.
    :return: Maximum value.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Find the minimum value in a list of numbers.
    :param numbers: List of numerical values.
    :return: Minimum value.
    """
    return min(numbers)

def main():
    print("Mathematical Operations on a List of Numbers")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Choose an operation (1-4): "))
        numbers = input("Enter a list of numbers separated by spaces: ")
        numbers = [float(num) for num in numbers.split()]

        if not numbers:
            raise ValueError("The list cannot be empty.")

        if choice == 1:
            result = calculate_sum(numbers)
        elif choice == 2:
            result = calculate_average(numbers)
        elif choice == 3:
            result = find_maximum(numbers)
        elif choice == 4:
            result = find_minimum(numbers)
        else:
            print("Invalid choice. Please select 1, 2, 3, or 4.")
            return

        print(f"Result: {result}")
    except ValueError as e:
        print(f"Error: {e}. Please enter valid input.")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()


Mathematical Operations on a List of Numbers
1. Sum
2. Average
3. Maximum
4. Minimum
Choose an operation (1-4): 1
Enter a list of numbers separated by spaces: 1 2 3 4 5
Result: 15.0


# 4.2 Exercise on List Manipulation:


# 1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    return lst[::2]

input_list = [1, 2, 3, 4, 5, 6]
output_list = extract_every_other(input_list)
print(output_list)

[1, 3, 5]


# 2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]


input_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4
output_list = get_sublist(input_list, start_index, end_index)
print(output_list)

[3, 4, 5]


# 3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    return lst[::-1]

input_list = [1, 2, 3, 4, 5]
output_list = reverse_list(input_list)
print(output_list)

[5, 4, 3, 2, 1]


# 4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    return lst[1:-1]


input_list = [1, 2, 3, 4, 5]
output_list = remove_first_last(input_list)
print(output_list)

[2, 3, 4]


# 5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
    return lst[:n]

input_list = [1, 2, 3, 4, 5]
n = 3
output_list = get_first_n(input_list, n)
print(output_list)

[1, 2, 3]


# 6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
    return lst[-n:]

input_list = [1, 2, 3, 4, 5]
n = 3
output_list = get_last_n(input_list, n)
print(output_list)

[3, 4, 5]


# 7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):

    return lst[-2::-2]


input_list = [1, 2, 3, 4, 5, 6]
output_list = reverse_skip(input_list)
print(output_list)

[5, 3, 1]


# 4.3 Exercise on Nested List:

# 1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def reverse_skip(lst):
    return lst[-2::-2]

input_list = [1, 2, 3, 4, 5, 6]
output_list = reverse_skip(input_list)
print(output_list)

[5, 3, 1]


# 2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
    current = lst
    for index in indices:
        current = current[index]
    return current

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
output = access_nested_element(lst, indices)
print(output)

6


# 3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:

– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    total = 0
    for element in lst:

        if isinstance(element, list):
            total += sum_nested(element)
        else:

            total += element
    return total

input_list = [[1, 2], [3, [4, 5]], 6]
output = sum_nested(input_list)
print(output)

21


# 4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    result = []
    for item in lst:

        if isinstance(item, list):
            result.append(remove_element(item, elem))
        else:

            if item != elem:
                result.append(item)
    return result

input_list = [[1, 2], [3, 2], [4, 5]]
elem = 2
output_list = remove_element(input_list, elem)
print(output_list)

[[1], [3], [4, 5]]


# 5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    max_val = None
    for item in lst:

        if isinstance(item, list):
            nested_max = find_max(item)

            if max_val is None or nested_max > max_val:
                max_val = nested_max
        else:

            if max_val is None or item > max_val:
                max_val = item
    return max_val

input_list = [[1, 2], [3, [4, 5]], 6]
output = find_max(input_list)
print(output)

6


# 6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:

        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:

            if item == elem:
                count += 1
    return count

input_list = [[1, 2], [2, 3], [2, 4], [2,6]]
elem = 2
output = count_occurrences(input_list, elem)
print(output)

4


# 7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    flattened = []
    for item in lst:

        if isinstance(item, list):
            flattened.extend(deep_flatten(item))
        else:

            flattened.append(item)
    return flattened

input_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
output_list = deep_flatten(input_list)
print(output_list)

[1, 2, 3, 4, 5, 6, 7, 8]


# 8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    total_sum = 0
    total_count = 0

    def recursive_helper(lst):
        nonlocal total_sum, total_count
        for item in lst:

            if isinstance(item, list):
                recursive_helper(item)
            else:

                total_sum += item
                total_count += 1

    recursive_helper(lst)


    return total_sum / total_count if total_count > 0 else 0

input_list = [[1, 2], [3, 4], [5, 6]]
output = average_nested(input_list)
print(output)

3.5


# 10 To - Do - NumPy

# 10.1 Basic Vector and Matrix Operation with Numpy


# Problem - 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


In [ ]:
import numpy as np

# Task 1:
empty_array = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_array)

# Task 2:
ones_array = np.ones((4, 2))
print("\n2. All ones 4x2 array:\n", ones_array)

# Task 3:
fill_value_array = np.full((3, 3), 5)
print("\n3. Array filled with value 5:\n", fill_value_array)

# Task 4:
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\n4. Zeros array with same shape as given array:\n", zeros_like_array)

# Task 5:
ones_like_array = np.ones_like(given_array)
print("\n5. Ones array with same shape as given array:\n", ones_like_array)

# Task 6:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Numpy array from list:\n", numpy_array)

1. Empty 2x2 array:
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

2. All ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with value 5:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

4. Zeros array with same shape as given array:
 [[0 0]
 [0 0]]

5. Ones array with same shape as given array:
 [[1 1]
 [1 1]]

6. Numpy array from list:
 [1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
# Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# Task 1:
array_range = np.arange(10, 50)
print("1. Array with values from 10 to 49:\n", array_range)

# Task 2:
matrix_3x3 = np.arange(0, 9).reshape(3, 3)
print("\n2. 3x3 matrix with values from 0 to 8:\n", matrix_3x3)

# Task 3:
identity_matrix = np.eye(3)
print("\n3. 3x3 identity matrix:\n", identity_matrix)

# Task 4:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n4. Random array of size 30:\n", random_array)
print("Mean of the array:", mean_value)

# Task 5:
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n5. 10x10 random array:\n", random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

# Task 6:
zero_array = np.zeros(10)
zero_array[4] = 1
print("\n6. Zero array with 5th element replaced by 1:\n", zero_array)

# Task 7:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:\n", reversed_arr)

# Task 8:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:\n", border_array)

# Task 9:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 checkerboard pattern:\n", checkerboard)

1. Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30:
 [0.42584436 0.7223849  0.66568674 0.86667318 0.63505721 0.8963853
 0.27484701 0.21519812 0.0639802  0.87863327 0.61169421 0.44285377
 0.71779477 0.63541844 0.81410925 0.12988994 0.60782054 0.26709434
 0.9748774  0.43633364 0.33576111 0.16298894 0.77520442 0.06408262
 0.49763849 0.29867259 0.75581466 0.71310668 0.91171592 0.93739195]
Mean of the array: 0.5578317996708596

5. 10x10 random array:
 [[0.17333424 0.39582043 0.34792363 0.11719648 0.61839269 0.67640243
  0.4904744  0.24455865 0.19059002 0.88438599]
 [0.81442617 0.78291723 0.81708784 0.32318687 0.56079018 0.66829619
  0.07932334 0.4950771  0.0471673  0.00334302]
 [0.11236668 0.90521636 0.5889092  0.23311561 0.78

# Problem - 3: Array Operations:
For the following arrays:

x = np.array([[1,2],[3,5]]) and

y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and

w = np.array([11,12]);
# Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1:
add_result = x + y
print("1. Addition of x and y:\n", add_result)

# Task 2:
subtract_result = x - y
print("\n2. Subtraction of x and y:\n", subtract_result)

# Task 3:
multiply_result = x * 2
print("\n3. Multiplication of x by 2:\n", multiply_result)

# Task 4:
square_result = x**2
print("\n4. Square of each element of x:\n", square_result)

# Task 5:
dot_vw = np.dot(v, w)  # Dot product of v and w
dot_xv = np.dot(x, v)  # Dot product of x and v
dot_xy = np.dot(x, y)  # Dot product of x and y
print("\n5. Dot products:")
print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:", dot_xv)
print("Dot product of x and y:\n", dot_xy)

# Task 6:
concatenate_row = np.concatenate((x, y), axis=0)
concatenate_col = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)
print("\n6. Concatenation:")
print("Concatenate x and y along row:\n", concatenate_row)
print("Concatenate v and w along column:\n", concatenate_col)

# Task 7:
try:
    concatenate_xv = np.concatenate((x, v))
    print("\n7. Concatenate x and v:\n", concatenate_xv)
except ValueError as e:
    print("\n7. Error when concatenating x and v:", e)

1. Addition of x and y:
 [[ 6  8]
 [10 13]]

2. Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

3. Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]

4. Square of each element of x:
 [[ 1  4]
 [ 9 25]]

5. Dot products:
Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

6. Concatenation:
Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
 [[ 9 11]
 [10 12]]

7. Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


# Problem - 4: Matrix Operations:


# For the following arrays:
A = np.array([[3,4],[7,8]]) and

B = np.array([[5,3],[2,1]]);

# Prove following with Numpy:
Prove A.A−1 = I.

Prove AB ̸= BA.

Prove (AB)T = BTAT

In [ ]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Task 1:
try:
    A_inv = np.linalg.inv(A)
    identity_check = np.dot(A, A_inv)
    print("1. A.A⁻¹:\n", identity_check)
except np.linalg.LinAlgError:
    print("1. A is not invertible.")

# Task 2:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("BA:\n", BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))

# Task 3:
AB_transpose = AB.T
B_transpose = B.T
A_transpose = A.T
BT_AT = np.dot(B_transpose, A_transpose)
print("\n3. (AB)ᵀ:\n", AB_transpose)
print("BᵀAᵀ:\n", BT_AT)
print("\nAre (AB)ᵀ and BᵀAᵀ equal?\n", np.array_equal(AB_transpose, BT_AT))

1. A.A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Are AB and BA equal? False

3. (AB)ᵀ:
 [[23 51]
 [13 29]]
BᵀAᵀ:
 [[23 51]
 [13 29]]

Are (AB)ᵀ and BᵀAᵀ equal?
 True


# Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
import numpy as np

A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])

try:
    A_inv = np.linalg.inv(A)
    print("Inverse of A:\n", A_inv)
except np.linalg.LinAlgError:
    print("Matrix A is not invertible.")

X = np.dot(A_inv, B)
print("\nSolution for X (x, y, z):\n", X)

Inverse of A:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution for X (x, y, z):
 [ 2.  1. -2.]


# 10.2 Experiment: How Fast is Numpy?

# 1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
#Using Python List

import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
result_list = [a + b for a, b in zip(list1, list2)]
end_time = time.time()

print("Time taken for element-wise addition using Python Lists:", end_time - start_time, "seconds")

Time taken for element-wise addition using Python Lists: 0.07033181190490723 seconds


In [ ]:
# Using NumPy Arrays

import numpy as np

array1 = np.arange(1000000)
array2 = np.arange(1000000)

start_time = time.time()
result_array = array1 + array2
end_time = time.time()

print("Time taken for element-wise addition using NumPy Arrays:", end_time - start_time, "seconds")

Time taken for element-wise addition using NumPy Arrays: 0.005162239074707031 seconds


# 2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
# Using Python Lists

import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
result_list = [a * b for a, b in zip(list1, list2)]
end_time = time.time()

print("Time taken for element-wise multiplication using Python Lists:", end_time - start_time, "seconds")

Time taken for element-wise multiplication using Python Lists: 0.08133339881896973 seconds


In [ ]:
# Using Numpy Arrays

import numpy as np

array1 = np.arange(1000000)
array2 = np.arange(1000000)
start_time = time.time()
result_array = array1 * array2
end_time = time.time()

print("Time taken for element-wise multiplication using NumPy Arrays:", end_time - start_time, "seconds")

Time taken for element-wise multiplication using NumPy Arrays: 0.0025682449340820312 seconds


# Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
# Using Python Lists

import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
dot_product = sum(a * b for a, b in zip(list1, list2))
end_time = time.time()
print("Time taken for dot product using Python Lists:", end_time - start_time, "seconds")
print("Dot product:", dot_product)


Time taken for dot product using Python Lists: 0.19704842567443848 seconds
Dot product: 333332833333500000


In [ ]:
# Using Numpy Arrays

import numpy as np

array1 = np.arange(1000000)
array2 = np.arange(1000000)

start_time = time.time()
dot_product = np.dot(array1, array2)
end_time = time.time()

print("Time taken for dot product using NumPy Arrays:", end_time - start_time, "seconds")
print("Dot product:", dot_product)

Time taken for dot product using NumPy Arrays: 0.0022063255310058594 seconds
Dot product: 333332833333500000


# Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

# Create two random matrices of size 1000x1000
# These matrices will be filled with random numbers
matrix_a = np.random.rand(1000, 1000)
matrix_b = np.random.rand(1000, 1000)

# Start the timer to measure how long the multiplication takes
start_time = time.time()

# Perform the matrix multiplication using numpy's dot function
result = np.dot(matrix_a, matrix_b)

# Stop the timer after the multiplication is done
end_time = time.time()

# Calculate the total time taken for the multiplication
time_taken = end_time - start_time

# Print the time taken in seconds
print(f"Time taken for matrix multiplication: {time_taken} seconds")


Time taken for matrix multiplication: 0.06685280799865723 seconds


In [ ]:
import numpy as np  # Import the NumPy library for numerical operations

# Create the first 1000x1000 matrix
# Each element is the sum of its row and column indices (i + j)
matrix1 = np.array([[i + j for j in range(1000)] for i in range(1000)])

# Create the second 1000x1000 matrix in the same way
matrix2 = np.array([[i + j for j in range(1000)] for i in range(1000)])

# Start timing the matrix multiplication process
start_time = time.time()

# Perform the matrix multiplication using NumPy's dot function
result = np.dot(matrix1, matrix2)

# Stop timing after the multiplication is complete
end_time = time.time()

# Print the total time taken for the matrix multiplication
print("Time taken for matrix multiplication using NumPy Arrays:", end_time - start_time, "seconds")


Time taken for matrix multiplication using NumPy Arrays: 1.2934625148773193 seconds


# Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [38]:
def convert_length(value, unit):
    """
    Convert length between meters (m) and feet (ft).
    :param value: The numerical value to convert.
    :param unit: The unit of the input value ('m' for meters, 'ft' for feet).
    :return: Converted value with appropriate unit.
    """
    if unit == 'm':
        return value * 3.28084, 'ft'
    elif unit == 'ft':
        return value / 3.28084, 'm'
    else:
        raise ValueError("Invalid unit for length conversion")

def convert_weight(value, unit):
    """
    Convert weight between kilograms (kg) and pounds (lbs).
    :param value: The numerical value to convert.
    :param unit: The unit of the input value ('kg' for kilograms, 'lbs' for pounds).
    :return: Converted value with appropriate unit.
    """
    if unit == 'kg':
        return value * 2.20462, 'lbs'
    elif unit == 'lbs':
        return value / 2.20462, 'kg'
    else:
        raise ValueError("Invalid unit for weight conversion")

def convert_volume(value, unit):
    """
    Convert volume between liters (L) and gallons (gal).
    :param value: The numerical value to convert.
    :param unit: The unit of the input value ('L' for liters, 'gal' for gallons).
    :return: Converted value with appropriate unit.
    """
    if unit == 'L':
        return value * 0.264172, 'gal'
    elif unit == 'gal':
        return value / 0.264172, 'L'
    else:
        raise ValueError("Invalid unit for volume conversion")

def main():
    print("Unit Converter: Length, Weight, Volume")
    print("1. Length (m <-> ft)")
    print("2. Weight (kg <-> lbs)")
    print("3. Volume (L <-> gal)")

    try:
        choice = int(input("Choose the type of conversion (1-3): "))
        value = float(input("Enter the value to convert: "))
        unit = input("Enter the unit (e.g., m, ft, kg, lbs, L, gal): ").strip().lower()

        if choice == 1:
            result, new_unit = convert_length(value, unit)
        elif choice == 2:
            result, new_unit = convert_weight(value, unit)
        elif choice == 3:
            result, new_unit = convert_volume(value, unit)
        else:
            print("Invalid choice. Please select 1, 2, or 3.")
            return

        print(f"Converted value: {result:.2f} {new_unit}")
    except ValueError as e:
        print(f"Error: {e}. Please enter valid input.")
    except Exception as e:
        print(f"Unexpected error: {e}")

# Run the main function
main()


Unit Converter: Length, Weight, Volume
1. Length (m <-> ft)
2. Weight (kg <-> lbs)
3. Volume (L <-> gal)
Choose the type of conversion (1-3): 1
Enter the value to convert: 10
Enter the unit (e.g., m, ft, kg, lbs, L, gal): m
Converted value: 32.81 ft


# Task - 2:

Create a Python program that performs various mathematical operations on a list of numbers

• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimumof the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, mini-mum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values orempty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, andreturn value.

In [39]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers.
    :param numbers: List of numerical values.
    :return: Sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculate the average of a list of numbers.
    :param numbers: List of numerical values.
    :return: Average of the numbers.
    """
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):
    """
    Find the maximum value in a list of numbers.
    :param numbers: List of numerical values.
    :return: Maximum value.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Find the minimum value in a list of numbers.
    :param numbers: List of numerical values.
    :return: Minimum value.
    """
    return min(numbers)

def main():
    print("Mathematical Operations on a List of Numbers")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Choose an operation (1-4): "))
        numbers = input("Enter a list of numbers separated by spaces: ")
        numbers = [float(num) for num in numbers.split()]

        if not numbers:
            raise ValueError("The list cannot be empty.")

        if choice == 1:
            result = calculate_sum(numbers)
        elif choice == 2:
            result = calculate_average(numbers)
        elif choice == 3:
            result = find_maximum(numbers)
        elif choice == 4:
            result = find_minimum(numbers)
        else:
            print("Invalid choice. Please select 1, 2, 3, or 4.")
            return

        print(f"Result: {result}")
    except ValueError as e:
        print(f"Error: {e}. Please enter valid input.")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()


Mathematical Operations on a List of Numbers
1. Sum
2. Average
3. Maximum
4. Minimum
Choose an operation (1-4): 1
Enter a list of numbers separated by spaces: 1 2 3 4 5
Result: 15.0


# 4.2 Exercise on List Manipulation:


# 1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [40]:
def extract_every_other(lst):
    return lst[::2]

input_list = [1, 2, 3, 4, 5, 6]
output_list = extract_every_other(input_list)
print(output_list)

[1, 3, 5]


# 2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [41]:
def get_sublist(lst, start, end):
    return lst[start:end+1]


input_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4
output_list = get_sublist(input_list, start_index, end_index)
print(output_list)

[3, 4, 5]


# 3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [42]:
def reverse_list(lst):
    return lst[::-1]

input_list = [1, 2, 3, 4, 5]
output_list = reverse_list(input_list)
print(output_list)

[5, 4, 3, 2, 1]


# 4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [43]:
def remove_first_last(lst):
    return lst[1:-1]


input_list = [1, 2, 3, 4, 5]
output_list = remove_first_last(input_list)
print(output_list)

[2, 3, 4]


# 5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [44]:
def get_first_n(lst, n):
    return lst[:n]

input_list = [1, 2, 3, 4, 5]
n = 3
output_list = get_first_n(input_list, n)
print(output_list)

[1, 2, 3]


# 6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [45]:
def get_last_n(lst, n):
    return lst[-n:]

input_list = [1, 2, 3, 4, 5]
n = 3
output_list = get_last_n(input_list, n)
print(output_list)

[3, 4, 5]


# 7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [46]:
def reverse_skip(lst):

    return lst[-2::-2]


input_list = [1, 2, 3, 4, 5, 6]
output_list = reverse_skip(input_list)
print(output_list)

[5, 3, 1]


# 4.3 Exercise on Nested List:

# 1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [47]:
def reverse_skip(lst):
    return lst[-2::-2]

input_list = [1, 2, 3, 4, 5, 6]
output_list = reverse_skip(input_list)
print(output_list)

[5, 3, 1]


# 2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [48]:
def access_nested_element(lst, indices):
    current = lst
    for index in indices:
        current = current[index]
    return current

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
output = access_nested_element(lst, indices)
print(output)

6


# 3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:

– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [49]:
def sum_nested(lst):
    total = 0
    for element in lst:

        if isinstance(element, list):
            total += sum_nested(element)
        else:

            total += element
    return total

input_list = [[1, 2], [3, [4, 5]], 6]
output = sum_nested(input_list)
print(output)

21


# 4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [50]:
def remove_element(lst, elem):
    result = []
    for item in lst:

        if isinstance(item, list):
            result.append(remove_element(item, elem))
        else:

            if item != elem:
                result.append(item)
    return result

input_list = [[1, 2], [3, 2], [4, 5]]
elem = 2
output_list = remove_element(input_list, elem)
print(output_list)

[[1], [3], [4, 5]]


# 5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [51]:
def find_max(lst):
    max_val = None
    for item in lst:

        if isinstance(item, list):
            nested_max = find_max(item)

            if max_val is None or nested_max > max_val:
                max_val = nested_max
        else:

            if max_val is None or item > max_val:
                max_val = item
    return max_val

input_list = [[1, 2], [3, [4, 5]], 6]
output = find_max(input_list)
print(output)

6


# 6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [52]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:

        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:

            if item == elem:
                count += 1
    return count

input_list = [[1, 2], [2, 3], [2, 4], [2,6]]
elem = 2
output = count_occurrences(input_list, elem)
print(output)

4


# 7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [53]:
def deep_flatten(lst):
    flattened = []
    for item in lst:

        if isinstance(item, list):
            flattened.extend(deep_flatten(item))
        else:

            flattened.append(item)
    return flattened

input_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
output_list = deep_flatten(input_list)
print(output_list)

[1, 2, 3, 4, 5, 6, 7, 8]


# 8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [54]:
def average_nested(lst):
    total_sum = 0
    total_count = 0

    def recursive_helper(lst):
        nonlocal total_sum, total_count
        for item in lst:

            if isinstance(item, list):
                recursive_helper(item)
            else:

                total_sum += item
                total_count += 1

    recursive_helper(lst)


    return total_sum / total_count if total_count > 0 else 0

input_list = [[1, 2], [3, 4], [5, 6]]
output = average_nested(input_list)
print(output)

3.5


# 10 To - Do - NumPy

# 10.1 Basic Vector and Matrix Operation with Numpy


# Problem - 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


In [55]:
import numpy as np

# Task 1:
empty_array = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_array)

# Task 2:
ones_array = np.ones((4, 2))
print("\n2. All ones 4x2 array:\n", ones_array)

# Task 3:
fill_value_array = np.full((3, 3), 5)
print("\n3. Array filled with value 5:\n", fill_value_array)

# Task 4:
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\n4. Zeros array with same shape as given array:\n", zeros_like_array)

# Task 5:
ones_like_array = np.ones_like(given_array)
print("\n5. Ones array with same shape as given array:\n", ones_like_array)

# Task 6:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Numpy array from list:\n", numpy_array)

1. Empty 2x2 array:
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

2. All ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with value 5:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

4. Zeros array with same shape as given array:
 [[0 0]
 [0 0]]

5. Ones array with same shape as given array:
 [[1 1]
 [1 1]]

6. Numpy array from list:
 [1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
# Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [56]:
import numpy as np

# Task 1:
array_range = np.arange(10, 50)
print("1. Array with values from 10 to 49:\n", array_range)

# Task 2:
matrix_3x3 = np.arange(0, 9).reshape(3, 3)
print("\n2. 3x3 matrix with values from 0 to 8:\n", matrix_3x3)

# Task 3:
identity_matrix = np.eye(3)
print("\n3. 3x3 identity matrix:\n", identity_matrix)

# Task 4:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n4. Random array of size 30:\n", random_array)
print("Mean of the array:", mean_value)

# Task 5:
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n5. 10x10 random array:\n", random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

# Task 6:
zero_array = np.zeros(10)
zero_array[4] = 1
print("\n6. Zero array with 5th element replaced by 1:\n", zero_array)

# Task 7:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:\n", reversed_arr)

# Task 8:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:\n", border_array)

# Task 9:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 checkerboard pattern:\n", checkerboard)

1. Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30:
 [0.42584436 0.7223849  0.66568674 0.86667318 0.63505721 0.8963853
 0.27484701 0.21519812 0.0639802  0.87863327 0.61169421 0.44285377
 0.71779477 0.63541844 0.81410925 0.12988994 0.60782054 0.26709434
 0.9748774  0.43633364 0.33576111 0.16298894 0.77520442 0.06408262
 0.49763849 0.29867259 0.75581466 0.71310668 0.91171592 0.93739195]
Mean of the array: 0.5578317996708596

5. 10x10 random array:
 [[0.17333424 0.39582043 0.34792363 0.11719648 0.61839269 0.67640243
  0.4904744  0.24455865 0.19059002 0.88438599]
 [0.81442617 0.78291723 0.81708784 0.32318687 0.56079018 0.66829619
  0.07932334 0.4950771  0.0471673  0.00334302]
 [0.11236668 0.90521636 0.5889092  0.23311561 0.78

# Problem - 3: Array Operations:
For the following arrays:

x = np.array([[1,2],[3,5]]) and

y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and

w = np.array([11,12]);
# Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [57]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1:
add_result = x + y
print("1. Addition of x and y:\n", add_result)

# Task 2:
subtract_result = x - y
print("\n2. Subtraction of x and y:\n", subtract_result)

# Task 3:
multiply_result = x * 2
print("\n3. Multiplication of x by 2:\n", multiply_result)

# Task 4:
square_result = x**2
print("\n4. Square of each element of x:\n", square_result)

# Task 5:
dot_vw = np.dot(v, w)  # Dot product of v and w
dot_xv = np.dot(x, v)  # Dot product of x and v
dot_xy = np.dot(x, y)  # Dot product of x and y
print("\n5. Dot products:")
print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:", dot_xv)
print("Dot product of x and y:\n", dot_xy)

# Task 6:
concatenate_row = np.concatenate((x, y), axis=0)
concatenate_col = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)
print("\n6. Concatenation:")
print("Concatenate x and y along row:\n", concatenate_row)
print("Concatenate v and w along column:\n", concatenate_col)

# Task 7:
try:
    concatenate_xv = np.concatenate((x, v))
    print("\n7. Concatenate x and v:\n", concatenate_xv)
except ValueError as e:
    print("\n7. Error when concatenating x and v:", e)

1. Addition of x and y:
 [[ 6  8]
 [10 13]]

2. Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

3. Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]

4. Square of each element of x:
 [[ 1  4]
 [ 9 25]]

5. Dot products:
Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

6. Concatenation:
Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
 [[ 9 11]
 [10 12]]

7. Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


# Problem - 4: Matrix Operations:


# For the following arrays:
A = np.array([[3,4],[7,8]]) and

B = np.array([[5,3],[2,1]]);

# Prove following with Numpy:
Prove A.A−1 = I.

Prove AB ̸= BA.

Prove (AB)T = BTAT

In [58]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Task 1:
try:
    A_inv = np.linalg.inv(A)
    identity_check = np.dot(A, A_inv)
    print("1. A.A⁻¹:\n", identity_check)
except np.linalg.LinAlgError:
    print("1. A is not invertible.")

# Task 2:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("BA:\n", BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))

# Task 3:
AB_transpose = AB.T
B_transpose = B.T
A_transpose = A.T
BT_AT = np.dot(B_transpose, A_transpose)
print("\n3. (AB)ᵀ:\n", AB_transpose)
print("BᵀAᵀ:\n", BT_AT)
print("\nAre (AB)ᵀ and BᵀAᵀ equal?\n", np.array_equal(AB_transpose, BT_AT))

1. A.A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Are AB and BA equal? False

3. (AB)ᵀ:
 [[23 51]
 [13 29]]
BᵀAᵀ:
 [[23 51]
 [13 29]]

Are (AB)ᵀ and BᵀAᵀ equal?
 True


# Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [59]:
import numpy as np

A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])

try:
    A_inv = np.linalg.inv(A)
    print("Inverse of A:\n", A_inv)
except np.linalg.LinAlgError:
    print("Matrix A is not invertible.")

X = np.dot(A_inv, B)
print("\nSolution for X (x, y, z):\n", X)

Inverse of A:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution for X (x, y, z):
 [ 2.  1. -2.]


# 10.2 Experiment: How Fast is Numpy?

# 1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [60]:
#Using Python List

import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
result_list = [a + b for a, b in zip(list1, list2)]
end_time = time.time()

print("Time taken for element-wise addition using Python Lists:", end_time - start_time, "seconds")

Time taken for element-wise addition using Python Lists: 0.07033181190490723 seconds


In [61]:
# Using NumPy Arrays

import numpy as np

array1 = np.arange(1000000)
array2 = np.arange(1000000)

start_time = time.time()
result_array = array1 + array2
end_time = time.time()

print("Time taken for element-wise addition using NumPy Arrays:", end_time - start_time, "seconds")

Time taken for element-wise addition using NumPy Arrays: 0.005162239074707031 seconds


# 2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [63]:
# Using Python Lists

import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
result_list = [a * b for a, b in zip(list1, list2)]
end_time = time.time()

print("Time taken for element-wise multiplication using Python Lists:", end_time - start_time, "seconds")

Time taken for element-wise multiplication using Python Lists: 0.08133339881896973 seconds


In [64]:
# Using Numpy Arrays

import numpy as np

array1 = np.arange(1000000)
array2 = np.arange(1000000)
start_time = time.time()
result_array = array1 * array2
end_time = time.time()

print("Time taken for element-wise multiplication using NumPy Arrays:", end_time - start_time, "seconds")

Time taken for element-wise multiplication using NumPy Arrays: 0.0025682449340820312 seconds


# Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [65]:
# Using Python Lists

import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
dot_product = sum(a * b for a, b in zip(list1, list2))
end_time = time.time()
print("Time taken for dot product using Python Lists:", end_time - start_time, "seconds")
print("Dot product:", dot_product)


Time taken for dot product using Python Lists: 0.19704842567443848 seconds
Dot product: 333332833333500000


In [66]:
# Using Numpy Arrays

import numpy as np

array1 = np.arange(1000000)
array2 = np.arange(1000000)

start_time = time.time()
dot_product = np.dot(array1, array2)
end_time = time.time()

print("Time taken for dot product using NumPy Arrays:", end_time - start_time, "seconds")
print("Dot product:", dot_product)

Time taken for dot product using NumPy Arrays: 0.0022063255310058594 seconds
Dot product: 333332833333500000


# Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [71]:
import numpy as np
import time

# Create two random matrices of size 1000x1000
# These matrices will be filled with random numbers
matrix_a = np.random.rand(1000, 1000)
matrix_b = np.random.rand(1000, 1000)

# Start the timer to measure how long the multiplication takes
start_time = time.time()

# Perform the matrix multiplication using numpy's dot function
result = np.dot(matrix_a, matrix_b)

# Stop the timer after the multiplication is done
end_time = time.time()

# Calculate the total time taken for the multiplication
time_taken = end_time - start_time

# Print the time taken in seconds
print(f"Time taken for matrix multiplication: {time_taken} seconds")


Time taken for matrix multiplication: 0.06685280799865723 seconds


In [74]:
import numpy as np  # Import the NumPy library for numerical operations

# Create the first 1000x1000 matrix
# Each element is the sum of its row and column indices (i + j)
matrix1 = np.array([[i + j for j in range(1000)] for i in range(1000)])

# Create the second 1000x1000 matrix in the same way
matrix2 = np.array([[i + j for j in range(1000)] for i in range(1000)])

# Start timing the matrix multiplication process
start_time = time.time()

# Perform the matrix multiplication using NumPy's dot function
result = np.dot(matrix1, matrix2)

# Stop timing after the multiplication is complete
end_time = time.time()

# Print the total time taken for the matrix multiplication
print("Time taken for matrix multiplication using NumPy Arrays:", end_time - start_time, "seconds")


Time taken for matrix multiplication using NumPy Arrays: 1.2934625148773193 seconds
